CREATE ROLE myuser WITH LOGIN PASSWORD '123';

GRANT ALL PRIVILEGES ON DATABASE activities2 TO myuser;

GRANT ALL PRIVILEGES ON TABLE movies TO myuser;

GRANT ALL PRIVILEGES ON TABLE poolvisits TO myuser;

GRANT ALL PRIVILEGES ON TABLE walks TO myuser;

GRANT ALL PRIVILEGES ON TABLE dailyactivities TO myuser;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE movies_id_seq TO myuser;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE walks_id_seq TO myuser;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE poolvisits_id_seq TO myuser;
